name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Just build it
        run: |
          sudo apt update && sudo apt install git libglib2.0-dev meson ninja-build valac libgee-0.8-dev libjson-glib-dev libgtk-3-dev libgcrypt-dev texlive-full
          mkdir build && cd build
          meson ..
          ninja -j$(nproc)
          ninja test
  get_fedora_releases:
    name: Get Fedora Releases
    runs-on: ubuntu-latest
    steps:
      - name: Query Fedora
        id: releases
        uses: sgallagher/get-fedora-releases-action@v1
    outputs:
      stable: ${{ steps.releases.outputs.stable }}
      development: ${{ steps.releases.outputs.development }}
      active: ${{ steps.releases.outputs.active }}
  unit_tests_fedora_stable:
    name: Build on Fedora
    needs: get_fedora_releases
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        release: ${{ fromJson(needs.get_fedora_releases.outputs.stable) }}
    container:
      image: quay.io/fedora/fedora:${{ matrix.release }}-x86_64
    steps:
       - uses: actions/checkout@v2
       - name: Just build it
         run: |
           sudo dnf install uncrustify git glib2-devel pkgconf-pkg-config meson ninja-build vala libgee-devel json-glib-devel gtk3-devel libgcrypt-devel texlive-scheme-medium -y
           mkdir build && cd build
           meson ..
           ninja -j$(nproc)
           ninja test
       - uses: actions/checkout@v2
       - name: Check formatting
         run: |
           . /etc/os-release
           if [ $VERSION_ID == "35" ]; then ./check_formatting; else exit 0; fi
